name: common_utilities
description: A Dart language Common Utility package, that makes your code faster,easier and cleaner. contains lots of useful functions for Dart primitive types (support all Flutter platforms)
version: 0.1.0
homepage: https://github.com/m-r-davari/dart_common_utilities

topics:
  - "common-utilities"
  - "common-utils"
  - "string-utils"
  - "utils"
  - "utility"

platforms:
  android:
  ios:
  web:

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0





