name: common_utilities
description: A Dart common utility package, currently supports string processing methods that makes your code cleaner.
version: 0.0.11
homepage: https://github.com/m-r-davari/dart_common_utilities

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
